### ISSUE TITLE
Can't build the docker image

### ISSUE THREAD

**Issue by inre** [Ogeon/rust-on-raspberry-pi#21]
I tried `docker build --tag rust-nightly-pi-cross .` and `docker build --build-arg RUST_GIT_REF=1.10.0 --tag rust-nightly-pi-cross .`. it stopped with an error:
The command '/bin/sh -c git clone $URL_GIT_RUST $HOME/rust; cd $HOME/rust; DEFAULT_RUST_GIT_REF=$(git tag --list | grep "^[0-9]+.[0-9]+.[0-9]+$" | sort -V | tail --lines 1); RUST_GIT_REF=${RUST_GIT_REF:-$DEFAULT_RUST_GIT_REF}; git reset --hard $RUST_GIT_REF; export TOOLCHAIN=$TOOLCHAIN_32 && [ $(uname -m) = 'x86_64' ] && export TOOLCHAIN=$TOOLCHAIN_64; export PATH=$TOOLCHAIN:$PATH; ./configure --target=arm-unknown-linux-gnueabihf --prefix=$HOME/pi-rust && make -j4 && make install;' returned a non-zero code: 2

Docker version 1.12.0-rc4, build e4a0dbc, experimental

**Comment by Ragnaroek** [comment]
same here, this PR fixes the version to rust 1.9 that is the last version that build in the container:
https://github.com/Ogeon/rust-on-raspberry-pi/pull/22 

My Docker-Version is:
Version 1.12.0-beta21 (build: 10868) (on MacOSX 10.11)

**Comment by Ogeon** [comment]
Hi, sorry for my late response. I have been on vacation and had more or less disconnected myself from most things.

There has recently been a bunch of problem with the approach in this guide, and some of them has known solutions and some don't, so everything has to be taken with a grain of salt, at the moment. I have been [meaning to rewrite parts of it](https://github.com/Ogeon/rust-on-raspberry-pi/issues/14) to simplify the process and completely avoid the compilation step, but I haven't gotten around to do it for various reasons. I suppose that this will be possible to transfer to the docker image, as well, but my docker knowledge is still very limited.

What I'm trying to say is that this guide is currently in a semi-incorrect state and that it is known. I did, however, not know that it broke in this way, as well, so thanks for letting me know. :+1: I would appreciate it if you could test the workaround from @Ragnaroek, and see if it works for you.

I'll also comment on the PR, and I should probably write a notice in the repo description to let people know that this guide is a bit outdated.

**Comment by Ragnaroek** [comment]
I run into the exact same error message while building the 1.10 version. I did not find a more detailed exception message to see what exactly went wrong.

I don't think the guide itself is outdated (it worked perfectly for me until the 1.10 version was released and I had to rebuild my docker images).

Building the image takes a long time. What do you think about publishing the build image to a public docker index/repository, so that everyone just can pull it?

**Comment by Ogeon** [comment]
> I run into the exact same error message while building the 1.10 version.

I'm just being thorough. :smile:

> What do you think about publishing the build image to a public docker index/repository, so that everyone just can pull it?

It is already officially built and distributed by the Rust team and that's why this guide is outdated. The setup procedure can be cut down to seconds, using rustup. I have already tested it ([here](https://github.com/Ogeon/rust-wiringpi/blob/86c67665e5a0a96c19fc6d21f09312858d2e0e5c/.travis.yml#L16-L27), for example) and it has been quite successful. I just need to write the prose.

Edit: Oh, and the dependency trick with .deb files seems to have stopped working. It looks like their file structure has changed.

**Comment by Ragnaroek** [comment]
Well I did not know about rustup! I guess this project is then obsolete. A hint to rustup
on readme would actually be nice :)

**Comment by Ogeon** [comment]
It's not completely obsolete. Rust is just half of the problem, and there's
still the need to set up linking and stuff. I haven't found a better
solution for that, yet.

**Comment by Ragnaroek** [comment]
see PR https://github.com/Ogeon/rust-on-raspberry-pi/pull/23
the docker image can now be build with rust 1.10.

**Comment by Ragnaroek** [comment]
I guess we can close this issue now?

**Comment by Ogeon** [comment]
Yeah, it's not really relevant anymore.
