### ISSUE TITLE
Instructions for cross-compiling ffi packages

### ISSUE THREAD

**Issue by jugglerchris** [Ogeon/rust-on-raspberry-pi#3]
Hi,
These instructions worked nicely, thanks - I'm impressed how things just work!
However, it doesn't cover using packages with foreign dependencies; in this case I was trying to use one of the sqlite3 crates. I'd be interested in some hints for making those work if you have any! 

Thanks again for the very useful guide!

**Comment by Ogeon** [comment]
I'm glad that they are useful :smile:

You have to make sure the library files for sqlite3 can be found in `gcc-sysroot` (see the section where `gcc` is pointed towards it). I think it have to be in the same place as on your Raspberry Pi, so you can just copy them from there.

**Comment by jugglerchris** [comment]
Hi,
Thanks for the reply!
I get an error when building:

```
   Compiling libsqlite3-sys v0.1.0
Build failed, waiting for other jobs to finish...
failed to run custom build command for `libsqlite3-sys v0.1.0`
Process didn't exit successfully: `<snip>/target/debug/build/libsqlite3-sys-89d2290e36b13660/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "pkg-config doesn\'t handle cross compilation. Use PKG_CONFIG_ALLOW_CROSS=1 to override"', <snip>/rust/src/libcore/result.rs:729
```

I tried setting PKG_CONFIG_ALLOW_CROSS=1, but it tried to link with my x86_64 libc.  :-)  I tried copying the .so files in, which didn't make a difference.

**Comment by Ogeon** [comment]
pkg-config is a tricky one. I had the same problem before, with openssl, but I don't remember if I managed to fix it by copying pkg-config files from my pi or if they changed the build script to work anyway. The problem is, as you have noticed, that pkg-config can't find the pi-specific library. It uses special files, where the paths are registered, to find them and you need to have those files and convince pkg-config to read them to make it work.

You could also try https://crates.io/crates/sqlite, which doesn't seem to care about where the library is, unless I missed something. I don't know if it's as good or not, but it may be worth it if it works.

**Comment by jugglerchris** [comment]
Hi,
The sqlite package seems to do the job, thanks!  I only chose one of the sqlite crates at random based on popularity, so as long as it works my immediate problem is solved.  :-)

Chris

**Comment by Ogeon** [comment]
That's nice to hear. Let's hope it's up for the job :smile:

I'm leaving this open for now, as a reminder to clarify that part of the guide and in case someone comes by with a real solution.

**Comment by tfnico** [comment]
@Ogeon I'm having problems cross-compiling my Rust project now, also because of openssl. 

I'm targeting a Pi running Raspbian, and I'm using a local 32 bit VM with Debian Jessie for cross-compiling. All the steps in your guide up until executing cross32 were successful. Here are my Cargo.toml dependencies:

```
websocket = "0.12.2"
tiny_http = "0.4.0"
protobuf = "1.0.2"
time = "0.1.32"
```

First I got some missing header files:

```
/home/vagrant/.cargo/registry/src/github.com-121aea75f9ef2ce2/openssl-sys-0.6.5/src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
```

I got around that by doing `export OPENSSL_INCLUDE_DIR=/usr/include` - and I probably did a `apt-get install libssl-dev` first.

Next up I got 

```
/usr/include/openssl/hmac.h:61:33: fatal error: openssl/opensslconf.h: No such file or directory
```

I got around that with this one:

```
ln -s /usr/include/i386-linux-gnu/openssl/opensslconf.h /usr/include/openssl
```

But now I immediately get a whole bunch of compilation problems when running `cross32 build`, for example:

<pre>
/usr/include/stdlib.h:951:12: error: storage class specified for parameter ‘getloadavg’
 extern int getloadavg (double __loadavg[], int __nelem)
            ^
/usr/include/stdlib.h:952:6: warning: ‘__nothrow__’ attribute ignored [-Wattributes]
      __THROW __nonnull ((1));
      ^
/usr/include/stdlib.h:955:31: fatal error: bits/stdlib-float.h: No such file or directory
 #include <bits/stdlib-float.h>
                               ^
compilation terminated.
thread '<main>' panicked at 'explicit panic', /home/vagrant/.cargo/registry/src/github.com-121aea75f9ef2ce2/gcc-0.3.13/src/lib.rs:510
</pre>

 If I understand correctly, the thing to do is:
- install libssl-dev on my Pi
- Find what files were installed on the Pi using something like `dpkg --listfiles libssl-dev`
- Copy those files to the custom sysroot on my cross-compiler VM, i.e. under `~/pi-tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot`
- unset the `OPENSSL_INCLUDE_DIR`, or at least point it inside the above sysroot

Am I on the right track here?

**Comment by Ogeon** [comment]
Yes, that should be it. The toolset is quite minimal, so you will have to mirror some dependencies like that. You shouldn't need to set `OPENSSL_INCLUDE_DIR`.

**Comment by tfnico** [comment]
@Ogeon thanks a lot! I got it working now. I noted down some lines on how I did it here: https://gist.github.com/tfnico/8e5265e97dc700a63d31

**Comment by Ogeon** [comment]
Oh, nice! What do you think about including your instructions this guide? Maybe as an appendix of some sort?

**Comment by smoltron** [comment]
I am trying to cross-compile this: https://github.com/plietar/librespot
Unfortunately it seems quite impossible, because of pkg-config in sysaudio, protobuf and some dns package. Otherwise your instructions were excellent.

**Comment by Ogeon** [comment]
Yea, I remember pkg-config being especially nasty, but I don't remember if I managed to make it work before the library I was using stopped depending on it. Anyway, I seem to remember something about some environment variables you can set to redirect it to the new sysroot. It will look for some special files there when searching for installed libraries.

Nice to hear that the guide helpful, even if that part didn't work :smile:
