### ISSUE TITLE
Compiling compiler fails at 6%

### ISSUE THREAD

**Issue by tompijls** [Ogeon/rust-on-raspberry-pi#30]
Hi,

Trying to follow the guide, but compiling the compiler fails. Any advice? I'll admit I'm quite a novice on this cross compiling, so sorry if I make trivial mistakes.

- Ubuntu 16.04, running in VMWare Fusion
- Rust 1.14.0

`tom@tom-virtual-machine:~/rust$ rustc -V`
`rustc 1.14.0 (e8a012324 2016-12-16)`
`tom@tom-virtual-machine:~/rust$ git reset --hard e8a012324`
`HEAD is now at e8a0123 Merge pull request #38415 from brson/beta-next`

When running `./configure --target=arm-unknown-linux-gnueabihf --prefix=$HOME/pi-rust` 
I get following error:
`configure: error: CFG_CMAKE needed, but unable to find any of: cmake`

I do following and now configure runs fine:
`sudo apt-get install cmake`

Then I run `make -j4 && make install` and get following error:

> [  9%] Building CXX object lib/MC/CMakeFiles/LLVMMC.dir/WinCOFFStreamer.cpp.o
[  9%] Linking CXX static library ../libLLVMMC.a
make[3]: Leaving directory '/home/tom/rust/x86_64-unknown-linux-gnu/llvm'
[  9%] Built target LLVMMC
make[2]: Leaving directory '/home/tom/rust/x86_64-unknown-linux-gnu/llvm'
Makefile:149: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/tom/rust/x86_64-unknown-linux-gnu/llvm'
/home/tom/rust/mk/llvm.mk:104: recipe for target '/home/tom/rust/x86_64-unknown-linux-gnu/llvm/llvm-finished-building' failed
make: *** [/home/tom/rust/x86_64-unknown-linux-gnu/llvm/llvm-finished-building] Error 2

**Comment by Ogeon** [comment]
Hi! This guide is very outdated by now. I would actually recommend against trying to build the compiler yourself, and instead use the official standard library, preferably through `rustup`.

First, make sure you have `rustup` installed and the preferred toolchain selected (for example `stable`), then install the standard libraries for ARM:

```
rustup target add arm-unknown-linux-gnueabihf
```

Then skip to the "Pointing Cargo in the Right Direction" section of the guide and follow it until you get to the "Running Cargo" section. There you will have to use a different script, since the process is simplified. You can use [this one](https://github.com/Ogeon/rust-wiringpi/blob/master/cross64), assuming that you are using a 64 bit host. Otherwise you can grab the 32 bit version from the same place. They are a bit different, so you can't follow all of the usage instructions to the letter, but the basics should work.

See the `install` section in [this script](https://github.com/Ogeon/rust-wiringpi/blob/master/.travis.yml) for a sort of condensed version. It's made for a CI setup, so take it with a grain of salt.

I hope this helps.

**Comment by tompijls** [comment]
Hi Ogeon,

I didn't manage yet to cross compile, but actually no longer require so. Seems Raspberry Pi 3 can actually compile rust applications natively.

Thought I post it for future reference.

Thanks a lot for your help though!

**Comment by Ogeon** [comment]
Ah, sweet! Feel free to ask again if you want to give cross compiling
another shot.
